#!/bin/bash

if [[ "a$1" != "a" ]]; then
	VERSION=$1
else
	VERSION=`git describe --dirty`
fi

CURVER=`grep "var version = " aisleriot.js | sed "s/.*\"\(.*\)\".*/\\1/"`
if [[ "$CURVER" == "$VERSION" ]]; then
	echo $VERSION
	exit
fi

tmp=mktemp

sed 's/\(var version = "\).*"/\1'"$VERSION"'"/' < aisleriot.js > $tmp
cp $tmp aisleriot.js
rm $tmp

echo $VERSION
